version: '3.2'

services:
  chess2brain:
    image: chess2brain
    networks:
           - traefik-public
    deploy:
      labels:
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.http.services.chess2brain.loadbalancer.server.port=80
        - traefik.http.routers.chess2brain.rule=Host(`chess2brain.com`)
        - traefik.http.routers.chess2brain.entrypoints=https
        - traefik.http.routers.chess2brain.tls.certresolver=le
        - traefik.http.routers.chess2brain.tls=true
        - traefik.http.routers.chess2brain-http.rule=HostRegexp(`{subdomain:[a-z]+}.chess2brain.com`, `chess2brain.com`)
        - traefik.http.routers.chess2brain-http.entrypoints=http
        - traefik.http.routers.chess2brain-http.middlewares=https-redirect

networks:
  traefik-public:
    external: true
  chess2brain_default: # fuucking docker
