version: "3"

services:
  client:
    image: nginx
    volumes:
      - ./:/usr/share/nginx/html
    deploy:
      labels:
        - traefik.docker.network=traefik-public
        - traefik.enable=true
        - traefik.http.services.chess2brain.loadbalancer.server.port=8000
        - traefik.http.routers.chess2brain.rule=Host(`chess2brain.com`)
        - traefik.http.routers.chess2brain.entrypoints=https
        - traefik.http.routers.chess2brain.tls.certresolver=le
        - traefik.http.routers.chess2brain.tls=true

networks:
  traefik-public:
    external: true
